const Config = {
  PROXIMITY_WINDOW_SECONDS: 15,
  MAX_CLOCK_SKEW_SECONDS: 30,
  BLE_HANDSHAKE_MAX_LATENCY_MS: 1500,
  HASH_ALGORITHM: 'sha256',
  SIGNATURE_ALGORITHM: 'SHA256',
};

module.exports = Config;
